[2025-01-10T01:38:47.915+0000] {processor.py:186} INFO - Started process (PID=4938) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:38:47.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:38:47.919+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:47.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:38:48.251+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:38:48.444+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.443+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:fetch_and_store_amazon_books
[2025-01-10T01:38:48.459+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.458+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:fetch_and_store_amazon_books
[2025-01-10T01:38:48.470+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.470+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:fetch_and_store_amazon_books
[2025-01-10T01:38:48.484+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.483+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:fetch_and_store_amazon_books
[2025-01-10T01:38:48.496+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.495+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:fetch_and_store_amazon_books
[2025-01-10T01:38:48.513+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.512+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:fetch_and_store_amazon_books
[2025-01-10T01:38:48.527+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.526+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:fetch_and_store_amazon_books
[2025-01-10T01:38:48.529+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.528+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:38:48.547+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.546+0000] {dag.py:3262} INFO - Creating ORM DAG for fetch_and_store_amazon_books
[2025-01-10T01:38:48.557+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:38:48.557+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2025-01-10T01:38:48.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.678 seconds
[2025-01-10T01:39:19.006+0000] {processor.py:186} INFO - Started process (PID=5001) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:39:19.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:39:19.009+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:39:19.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:39:19.084+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:39:19.104+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:39:19.103+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:39:19.125+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:39:19.125+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2025-01-10T01:39:19.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.146 seconds
[2025-01-10T01:39:50.015+0000] {processor.py:186} INFO - Started process (PID=5065) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:39:50.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:39:50.019+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:39:50.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:39:50.092+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:39:50.108+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:39:50.108+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:39:50.128+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:39:50.128+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2025-01-10T01:39:50.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.136 seconds
[2025-01-10T01:40:29.294+0000] {processor.py:186} INFO - Started process (PID=5130) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:40:29.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:40:29.321+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:40:29.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:40:29.744+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:40:29.825+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:40:29.820+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:40:30.194+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.915 seconds
[2025-01-10T01:41:08.390+0000] {processor.py:186} INFO - Started process (PID=5168) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:41:08.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:41:08.419+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:41:08.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:41:09.151+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:41:09.308+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:41:09.306+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:41:09.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.130 seconds
[2025-01-10T01:42:20.211+0000] {processor.py:186} INFO - Started process (PID=5235) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:42:20.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:42:20.217+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:42:20.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:42:20.515+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:42:20.676+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:42:20.675+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:42:20.811+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.610 seconds
[2025-01-10T01:43:11.703+0000] {processor.py:186} INFO - Started process (PID=5254) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:43:11.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:43:11.734+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:11.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:43:12.417+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:43:12.512+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:12.511+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-20T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': '8f0167ad-12ee-46ae-8c18-30ca270e9af2'}
[2025-01-10T01:43:12.618+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:12.626+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:21.050256+00:00 end:2025-01-10 01:43:12.606280+00:00 duration:51.556024
[2025-01-10T01:43:12.640+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-20 00:00:00+00:00: scheduled__2024-06-20T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:06.414231+00:00. externally triggered: False>
[2025-01-10T01:43:12.643+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-20T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': '8f0167ad-12ee-46ae-8c18-30ca270e9af2'}
[2025-01-10T01:43:12.648+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:12.647+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-20T00:00:00+00:00, execution_date=20240620T000000, start_date=20250110T014221, end_date=20250110T014312
[2025-01-10T01:43:12.770+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:12.770+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-20T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:12.845+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:12.845+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:43:12.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.274 seconds
[2025-01-10T01:43:21.925+0000] {processor.py:186} INFO - Started process (PID=5304) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:43:21.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:43:21.936+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:21.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:43:22.056+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:43:22.078+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.078+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'c39d2827-495e-4aff-8cc5-cb5fbe30121b'}
[2025-01-10T01:43:22.103+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.104+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:19.930328+00:00 end:2025-01-10 01:43:22.102875+00:00 duration:62.172547
[2025-01-10T01:43:22.105+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-21 00:00:00+00:00: scheduled__2024-06-21T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:06.859084+00:00. externally triggered: False>
[2025-01-10T01:43:22.105+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'c39d2827-495e-4aff-8cc5-cb5fbe30121b'}
[2025-01-10T01:43:22.106+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.106+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-21T00:00:00+00:00, execution_date=20240621T000000, start_date=20250110T014219, end_date=20250110T014322
[2025-01-10T01:43:22.126+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.126+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-21T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.130+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.130+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-22T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': '8eefe202-8a25-4773-92a6-601f7b80e426'}
[2025-01-10T01:43:22.139+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.140+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.446100+00:00 end:2025-01-10 01:43:22.139398+00:00 duration:61.693298
[2025-01-10T01:43:22.140+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-22 00:00:00+00:00: scheduled__2024-06-22T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:07.058868+00:00. externally triggered: False>
[2025-01-10T01:43:22.141+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-22T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': '8eefe202-8a25-4773-92a6-601f7b80e426'}
[2025-01-10T01:43:22.141+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.141+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20250110T014220, end_date=20250110T014322
[2025-01-10T01:43:22.148+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.148+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-22T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.151+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.151+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'fc013e12-0769-4b7c-aa11-288fdd915c9b'}
[2025-01-10T01:43:22.159+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.160+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.446161+00:00 end:2025-01-10 01:43:22.159438+00:00 duration:61.713277
[2025-01-10T01:43:22.160+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-23 00:00:00+00:00: scheduled__2024-06-23T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:07.294561+00:00. externally triggered: False>
[2025-01-10T01:43:22.160+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'fc013e12-0769-4b7c-aa11-288fdd915c9b'}
[2025-01-10T01:43:22.161+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.161+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20250110T014220, end_date=20250110T014322
[2025-01-10T01:43:22.168+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.168+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-23T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.171+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.170+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f3be5c12-2106-4398-8fac-fe9a1eceeaaf'}
[2025-01-10T01:43:22.178+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.178+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.222567+00:00 end:2025-01-10 01:43:22.178179+00:00 duration:61.955612
[2025-01-10T01:43:22.179+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-30 00:00:00+00:00: scheduled__2024-06-30T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:13.645687+00:00. externally triggered: False>
[2025-01-10T01:43:22.179+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f3be5c12-2106-4398-8fac-fe9a1eceeaaf'}
[2025-01-10T01:43:22.180+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.180+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20250110T014220, end_date=20250110T014322
[2025-01-10T01:43:22.187+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.187+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-30T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.190+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.190+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-01T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'ce706c4d-cd56-4405-9f46-f0d9b7c96dbf'}
[2025-01-10T01:43:22.198+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.198+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.464717+00:00 end:2025-01-10 01:43:22.198243+00:00 duration:61.733526
[2025-01-10T01:43:22.199+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-07-01 00:00:00+00:00: scheduled__2024-07-01T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:14.180807+00:00. externally triggered: False>
[2025-01-10T01:43:22.199+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-01T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'ce706c4d-cd56-4405-9f46-f0d9b7c96dbf'}
[2025-01-10T01:43:22.200+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.200+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20250110T014220, end_date=20250110T014322
[2025-01-10T01:43:22.206+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.206+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-07-01T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.209+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.209+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'a31b3480-3e83-456e-81dc-5cb4ef5a4417'}
[2025-01-10T01:43:22.218+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.219+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.201538+00:00 end:2025-01-10 01:43:22.218335+00:00 duration:62.016797
[2025-01-10T01:43:22.219+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-24 00:00:00+00:00: scheduled__2024-06-24T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:07.591802+00:00. externally triggered: False>
[2025-01-10T01:43:22.220+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'a31b3480-3e83-456e-81dc-5cb4ef5a4417'}
[2025-01-10T01:43:22.221+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.221+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20250110T014220, end_date=20250110T014322
[2025-01-10T01:43:22.229+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.228+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-24T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.232+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.232+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-27T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f2240281-6135-4653-808f-add793289387'}
[2025-01-10T01:43:22.240+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.240+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.659640+00:00 end:2025-01-10 01:43:22.239918+00:00 duration:61.580278
[2025-01-10T01:43:22.241+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-27 00:00:00+00:00: scheduled__2024-06-27T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:09.145796+00:00. externally triggered: False>
[2025-01-10T01:43:22.241+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-27T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f2240281-6135-4653-808f-add793289387'}
[2025-01-10T01:43:22.241+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.241+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20250110T014220, end_date=20250110T014322
[2025-01-10T01:43:22.250+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.250+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-27T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.255+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.254+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'c39d2827-495e-4aff-8cc5-cb5fbe30121b'}
[2025-01-10T01:43:22.261+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:22.262+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:19.930328+00:00 end:2025-01-10 01:43:22.258083+00:00 duration:62.327755
[2025-01-10T01:43:22.263+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-21 00:00:00+00:00: scheduled__2024-06-21T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:06.859084+00:00. externally triggered: False>
[2025-01-10T01:43:22.263+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-21T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'c39d2827-495e-4aff-8cc5-cb5fbe30121b'}
[2025-01-10T01:43:22.263+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.263+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-21T00:00:00+00:00, execution_date=20240621T000000, start_date=20250110T014219, end_date=20250110T014322
[2025-01-10T01:43:22.271+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.271+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-21T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:22.284+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:22.284+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:43:22.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.459 seconds
[2025-01-10T01:43:52.770+0000] {processor.py:186} INFO - Started process (PID=5367) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:43:52.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:43:52.774+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:43:52.850+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:43:52.866+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.866+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-22T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': '8eefe202-8a25-4773-92a6-601f7b80e426'}
[2025-01-10T01:43:52.883+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:52.883+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.446100+00:00 end:2025-01-10 01:43:52.872541+00:00 duration:92.426441
[2025-01-10T01:43:52.883+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-22 00:00:00+00:00: scheduled__2024-06-22T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:07.058868+00:00. externally triggered: False>
[2025-01-10T01:43:52.884+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-22T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': '8eefe202-8a25-4773-92a6-601f7b80e426'}
[2025-01-10T01:43:52.885+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.884+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20250110T014220, end_date=20250110T014352
[2025-01-10T01:43:52.896+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.896+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-22T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:52.900+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.900+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'fc013e12-0769-4b7c-aa11-288fdd915c9b'}
[2025-01-10T01:43:52.909+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:52.910+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.446161+00:00 end:2025-01-10 01:43:52.905860+00:00 duration:92.459699
[2025-01-10T01:43:52.910+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-23 00:00:00+00:00: scheduled__2024-06-23T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:07.294561+00:00. externally triggered: False>
[2025-01-10T01:43:52.910+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-23T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'fc013e12-0769-4b7c-aa11-288fdd915c9b'}
[2025-01-10T01:43:52.911+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.911+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20250110T014220, end_date=20250110T014352
[2025-01-10T01:43:52.917+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.917+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-23T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:52.920+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.920+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f3be5c12-2106-4398-8fac-fe9a1eceeaaf'}
[2025-01-10T01:43:52.926+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:52.927+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.222567+00:00 end:2025-01-10 01:43:52.923226+00:00 duration:92.700659
[2025-01-10T01:43:52.927+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-30 00:00:00+00:00: scheduled__2024-06-30T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:13.645687+00:00. externally triggered: False>
[2025-01-10T01:43:52.928+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-30T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f3be5c12-2106-4398-8fac-fe9a1eceeaaf'}
[2025-01-10T01:43:52.928+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.928+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20250110T014220, end_date=20250110T014352
[2025-01-10T01:43:52.934+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.934+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-30T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:52.937+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.936+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-01T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'ce706c4d-cd56-4405-9f46-f0d9b7c96dbf'}
[2025-01-10T01:43:52.943+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:52.943+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.464717+00:00 end:2025-01-10 01:43:52.940038+00:00 duration:92.475321
[2025-01-10T01:43:52.943+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-07-01 00:00:00+00:00: scheduled__2024-07-01T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:14.180807+00:00. externally triggered: False>
[2025-01-10T01:43:52.944+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-07-01T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'ce706c4d-cd56-4405-9f46-f0d9b7c96dbf'}
[2025-01-10T01:43:52.944+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.944+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20250110T014220, end_date=20250110T014352
[2025-01-10T01:43:52.950+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.950+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-07-01T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:52.953+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.953+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'a31b3480-3e83-456e-81dc-5cb4ef5a4417'}
[2025-01-10T01:43:52.961+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:52.962+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.201538+00:00 end:2025-01-10 01:43:52.956739+00:00 duration:92.755201
[2025-01-10T01:43:52.962+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-24 00:00:00+00:00: scheduled__2024-06-24T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:07.591802+00:00. externally triggered: False>
[2025-01-10T01:43:52.962+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-24T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'a31b3480-3e83-456e-81dc-5cb4ef5a4417'}
[2025-01-10T01:43:52.963+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.963+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20250110T014220, end_date=20250110T014352
[2025-01-10T01:43:52.969+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.968+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-24T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:52.972+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.972+0000] {taskinstance.py:3312} ERROR - {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-27T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f2240281-6135-4653-808f-add793289387'}
[2025-01-10T01:43:52.979+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-10T01:43:52.979+0000] {logging_mixin.py:190} INFO - Task start:2025-01-10 01:42:20.659640+00:00 end:2025-01-10 01:43:52.975275+00:00 duration:92.315635
[2025-01-10T01:43:52.979+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_book_data> dag:<DAG: fetch_and_store_amazon_books> dagrun:<DagRun fetch_and_store_amazon_books @ 2024-06-27 00:00:00+00:00: scheduled__2024-06-27T00:00:00+00:00, state:running, queued_at: 2025-01-10 01:40:09.145796+00:00. externally triggered: False>
[2025-01-10T01:43:52.979+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'fetch_and_store_amazon_books', 'Task Id': 'fetch_book_data', 'Run Id': 'scheduled__2024-06-27T00:00:00+00:00', 'Hostname': 'a0216be1203f', 'External Executor Id': 'f2240281-6135-4653-808f-add793289387'}
[2025-01-10T01:43:52.980+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.980+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=fetch_book_data, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20250110T014220, end_date=20250110T014352
[2025-01-10T01:43:52.986+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.986+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: fetch_and_store_amazon_books.fetch_book_data scheduled__2024-06-27T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-10T01:43:52.996+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:43:52.996+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-10T01:43:53.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.284 seconds
[2025-01-10T01:44:23.597+0000] {processor.py:186} INFO - Started process (PID=5428) to work on /opt/airflow/dags/dag.py
[2025-01-10T01:44:23.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-01-10T01:44:23.605+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:44:23.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-01-10T01:44:23.782+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-01-10T01:44:23.823+0000] {logging_mixin.py:190} INFO - [2025-01-10T01:44:23.822+0000] {dag.py:3239} INFO - Sync 1 DAGs
